
###Get Token
GET http://localhost:3001/api/token HTTP/1.1

###Post Text
POST http://localhost:3001/api/text HTTP/1.1
content-type: application/json

{
    "token": "NG0Wn", 
    "textContent": " Apa Sajalah" 
}